# Site settings
title: torino.hacknight.it
email: riccardo@menodizero.it
description: "torino.hacknight.it: hacking free software sotto la mole"
baseurl: ""
url: "http://torino.hacknight.it"
twitter_username: tohacknight
github_username: tohacknight

# Build settings
markdown: kramdown
permalink: pretty

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Dove siamo
  social: Dove puoi trovarci
  credits: Partners

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/tohacknight

# Postal address (add as many lines as necessary)
address:
  - line: Torino

# Credits content
credits: ''
